; STM32 Nucleo-C031C6 (Cortex-M0+) — FreeRTOS — simulable dans Wokwi for VS Code
[env:nucleo]
platform = ststm32
board = nucleo_c031c6
framework = arduino
lib_deps =
  stm32duino/STM32duino FreeRTOS
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
