; STM32 Nucleo-C031C6 (Cortex-M0+, 32 Ko flash / 12 Ko RAM) — FreeRTOS — Wokwi for VS Code
[env:nucleo]
platform = ststm32
board = nucleo_c031c6
framework = arduino
lib_deps =
  stm32duino/STM32duino FreeRTOS
; Plan B si la mémoire flash déborde encore : activer l'optimisation à l'édition
; de liens (LTO) en retirant le ";" devant la ligne suivante.
; extra_scripts = pre:lto.py
