; Projet PlatformIO — compile le firmware sur TON PC, puis Wokwi le simule dans VS Code
[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson@^7
  beegee-tokyo/DHT sensor library for ESPx
  adafruit/Adafruit MPU6050
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
