; STM32 "Blue Pill" (STM32F103C8) — FreeRTOS — simulable dans Wokwi for VS Code
[env:bluepill]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
lib_deps =
  stm32duino/STM32duino FreeRTOS
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
